### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by bdagenais** [beyerch/DHP_Kepler#2]
I am trying to build the firmaware using Atmel Studio 7 and I get some errors, can you verify the code ?

------ Build started: Project: KeplerFirmware, Configuration: Debug ARM ------
Build started.
Project "KeplerFirmware.cproj" (default targets):
Target "PreBuildEvent" skipped, due to false condition; ('$(PreBuildEvent)'!='') was evaluated as (''!='').
Target "CoreBuild" in file "C:\Program Files (x86)\Atmel\Studio\7.0\Vs\Compiler.targets" from project "C:\Users\bdagenais\Documents\DHP_Kepler\DHP_Kepler-master\Firmware\KeplerFirmware.cproj" (target "Build" depends on it):
	Task "RunCompilerTask"
		Shell Utils Path C:\Program Files (x86)\Atmel\Studio\7.0\shellUtils
		C:\Program Files (x86)\Atmel\Studio\7.0\shellUtils\make.exe all --jobs 4 --output-sync 
		Building file: ../src/ADC/adc.c
		Invoking: ARM/GNU C Compiler : 6.3.1
		"C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\arm\arm-gnu-toolchain\bin\arm-none-eabi-gcc.exe"  -x c -mthumb -D__SAM4E8C__ -DDEBUG -DBOARD=SAM4E_EK -Dscanf=iscanf -DARM_MATH_CM4=true -Dprintf=iprintf -D__SAM4E16E__ -DUDD_ENABLE  -I"../src/ASF/common/boards" -I"../src/ASF/sam/utils" -I"../src/ASF/sam/utils/header_files" -I"../src/ASF/sam/utils/preprocessor" -I"../src/ASF/thirdparty/CMSIS/Include" -I"../src/ASF/thirdparty/CMSIS/Lib/GCC" -I"../src/ASF/sam/utils/fpu" -I"../src/ASF/common/utils" -I"../src/ASF/sam/utils/cmsis/sam4e/include" -I"../src/ASF/sam/utils/cmsis/sam4e/source/templates" -I"../src/ASF/sam/boards/sam4e_ek" -I"../src/ASF/sam/boards" -I"../src/ASF/common/services/ioport" -I"../src/ASF/common/services/clock" -I"../src/ASF/sam/drivers/pmc" -I"../src" -I"../src/config" -I"../src/ASF/sam/drivers/matrix" -I"../src/ASF/sam/drivers/pio" -I"../src/ASF/common/services/sleepmgr" -I"../src/ASF/common/services/usb" -I"../src/ASF/common/services/usb/class/cdc" -I"../src/ASF/common/services/usb/class/cdc/device" -I"../src/ASF/common/services/usb/udc" -I"../src/ASF/sam/drivers/udp" -I"../src/UI" -I"C:\Users\adeck\Documents\DHP\Firmware\Kepler\KAVI_Firmware_CPP\KeplerFirmware\KeplerFirmware\Debug\src\USB" -I"../src/USB" -I"../src/CommandResponse" -I"../src/CommandResponse/FIFO" -I"../src/CommandResponse/Message" -I"../src/CommandResponse/Error" -I"../src/Vehicle" -I"../src/Vehicle/J1850/VPW" -I"../src/ASF/sam/drivers/tc" -I"../src/ASF/sam/drivers/efc" -I"../src/ASF/sam/services/flash_efc" -I"../src/Security" -I"../src/ASF/sam/drivers/can" -I"../src/RunTimer" -I"../src/ASF/sam/drivers/uart" -I"../src/Console" -I"../../../libs/VehicleCommunicationLib/ISOTP" -I"../src/ASF/sam/drivers/afec" -I"../src/ADC" -I"../src/Filter" -I"../src/Vehicle/CAN" -I"../src/ASF/common/services/delay"  -O0 -fdata-sections -ffunction-sections -mlong-calls -g3 -Wall -mcpu=cortex-m4 -c -pipe -fno-strict-aliasing -Wall -Wstrict-prototypes -Wmissing-prototypes -Werror-implicit-function-declaration -Wpointer-arith -std=gnu99 -ffunction-sections -fdata-sections -Wchar-subscripts -Wcomment -Wformat=2 -Wimplicit-int -Wmain -Wparentheses -Wsequence-point -Wreturn-type -Wswitch -Wtrigraphs -Wunused -Wuninitialized -Wunknown-pragmas -Wfloat-equal -Wundef -Wshadow -Wbad-function-cast -Wwrite-strings -Wsign-compare -Waggregate-return -Wmissing-declarations -Wformat -Wmissing-format-attribute -Wno-deprecated-declarations -Wpacked -Wredundant-decls -Wnested-externs -Wlong-long -Wunreachable-code -Wcast-align --param max-inline-insns-single=500 -mfloat-abi=softfp -mfpu=fpv4-sp-d16 -MD -MP -MF "src/ADC/adc.d" -MT"src/ADC/adc.d" -MT"src/ADC/adc.o"   -o "src/ADC/adc.o" "../src/ADC/adc.c" 
C:\Users\bdagenais\Documents\DHP_Kepler\DHP_Kepler-master\Firmware\Debug\Makefile(340,1): error: recipe for target 'src/ADC/adc.o' failed
		In file included from ../src/CommandResponse/Message/MessageHandler.h:13:0,
		                 from ../src/config/conf_usb.h:170,
		                 from ../src/ASF/common/services/usb/class/cdc/device/udi_cdc.h:50,
		                 from ../src/asf.h:122,
		                 from ../src/ADC/adc.h:12,
		                 from ../src/ADC/adc.c:7:
C:\Users\bdagenais\Documents\DHP_Kepler\DHP_Kepler-master\Firmware\src\CommandResponse\Message\Messages.h(46,1): warning: "/*" within comment [-Wcomment]
		 /*________________________________|___________________|_________________________________________|___________________________*/
		  
		In file included from ../src/CommandResponse/Message/MessageHandler.h:15:0,
		                 from ../src/config/conf_usb.h:170,
		                 from ../src/ASF/common/services/usb/class/cdc/device/udi_cdc.h:50,
		                 from ../src/asf.h:122,
		                 from ../src/ADC/adc.h:12,
		                 from ../src/ADC/adc.c:7:
C:\Users\bdagenais\Documents\DHP_Kepler\DHP_Kepler-master\Firmware\src\KeplerConfiguration.h(14,0): warning: "cpu_ms_2_cy" redefined
		 #define cpu_ms_2_cy(ms, f_cpu) (((uint64_t)(ms) * (f_cpu) / 6 + 999) / 1e3)
		 
		In file included from ../src/ASF/common/services/delay/delay.h:62:0,
		                 from ../src/asf.h:66,
		                 from ../src/ADC/adc.h:12,
		                 from ../src/ADC/adc.c:7:
C:\Users\bdagenais\Documents\DHP_Kepler\DHP_Kepler-master\Firmware\src\ASF\common\services\delay\sam\cycle_counter.h(108,0): info: this is the location of the previous definition
		 #  define cpu_ms_2_cy(ms, f_cpu)  \
		 
		In file included from ../src/Vehicle/CAN/CanFilter.h:13:0,
		                 from ../src/CommandResponse/Message/MessageHandler.h:23,
		                 from ../src/config/conf_usb.h:170,
		                 from ../src/ASF/common/services/usb/class/cdc/device/udi_cdc.h:50,
		                 from ../src/asf.h:122,
		                 from ../src/ADC/adc.h:12,
		                 from ../src/ADC/adc.c:7:
C:\Users\bdagenais\Documents\DHP_Kepler\DHP_Kepler-master\Firmware\src\Vehicle\CAN\kcan.h(15,25): error: isotp_types.h: No such file or directory
		 #include "isotp_types.h"
		                         ^
		compilation terminated.
		make: *** [src/ADC/adc.o] Error 1
		make: *** Waiting for unfinished jobs....
		Building file: ../src/ASF/common/services/usb/class/cdc/device/udi_cdc_desc.c
		Invoking: ARM/GNU C Compiler : 6.3.1
		"C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\arm\arm-gnu-toolchain\bin\arm-none-eabi-gcc.exe"  -x c -mthumb -D__SAM4E8C__ -DDEBUG -DBOARD=SAM4E_EK -Dscanf=iscanf -DARM_MATH_CM4=true -Dprintf=iprintf -D__SAM4E16E__ -DUDD_ENABLE  -I"../src/ASF/common/boards" -I"../src/ASF/sam/utils" -I"../src/ASF/sam/utils/header_files" -I"../src/ASF/sam/utils/preprocessor" -I"../src/ASF/thirdparty/CMSIS/Include" -I"../src/ASF/thirdparty/CMSIS/Lib/GCC" -I"../src/ASF/sam/utils/fpu" -I"../src/ASF/common/utils" -I"../src/ASF/sam/utils/cmsis/sam4e/include" -I"../src/ASF/sam/utils/cmsis/sam4e/source/templates" -I"../src/ASF/sam/boards/sam4e_ek" -I"../src/ASF/sam/boards" -I"../src/ASF/common/services/ioport" -I"../src/ASF/common/services/clock" -I"../src/ASF/sam/drivers/pmc" -I"../src" -I"../src/config" -I"../src/ASF/sam/drivers/matrix" -I"../src/ASF/sam/drivers/pio" -I"../src/ASF/common/services/sleepmgr" -I"../src/ASF/common/services/usb" -I"../src/ASF/common/services/usb/class/cdc" -I"../src/ASF/common/services/usb/class/cdc/device" -I"../src/ASF/common/services/usb/udc" -I"../src/ASF/sam/drivers/udp" -I"../src/UI" -I"C:\Users\adeck\Documents\DHP\Firmware\Kepler\KAVI_Firmware_CPP\KeplerFirmware\KeplerFirmware\Debug\src\USB" -I"../src/USB" -I"../src/CommandResponse" -I"../src/CommandResponse/FIFO" -I"../src/CommandResponse/Message" -I"../src/CommandResponse/Error" -I"../src/Vehicle" -I"../src/Vehicle/J1850/VPW" -I"../src/ASF/sam/drivers/tc" -I"../src/ASF/sam/drivers/efc" -I"../src/ASF/sam/services/flash_efc" -I"../src/Security" -I"../src/ASF/sam/drivers/can" -I"../src/RunTimer" -I"../src/ASF/sam/drivers/uart" -I"../src/Console" -I"../../../libs/VehicleCommunicationLib/ISOTP" -I"../src/ASF/sam/drivers/afec" -I"../src/ADC" -I"../src/Filter" -I"../src/Vehicle/CAN" -I"../src/ASF/common/services/delay"  -O0 -fdata-sections -ffunction-sections -mlong-calls -g3 -Wall -mcpu=cortex-m4 -c -pipe -fno-strict-aliasing -Wall -Wstrict-prototypes -Wmissing-prototypes -Werror-implicit-function-declaration -Wpointer-arith -std=gnu99 -ffunction-sections -fdata-sections -Wchar-subscripts -Wcomment -Wformat=2 -Wimplicit-int -Wmain -Wparentheses -Wsequence-point -Wreturn-type -Wswitch -Wtrigraphs -Wunused -Wuninitialized -Wunknown-pragmas -Wfloat-equal -Wundef -Wshadow -Wbad-function-cast -Wwrite-strings -Wsign-compare -Waggregate-return -Wmissing-declarations -Wformat -Wmissing-format-attribute -Wno-deprecated-declarations -Wpacked -Wredundant-decls -Wnested-externs -Wlong-long -Wunreachable-code -Wcast-align --param max-inline-insns-single=500 -mfloat-abi=softfp -mfpu=fpv4-sp-d16 -MD -MP -MF "src/ASF/common/services/usb/class/cdc/device/udi_cdc_desc.d" -MT"src/ASF/common/services/usb/class/cdc/device/udi_cdc_desc.d" -MT"src/ASF/common/services/usb/class/cdc/device/udi_cdc_desc.o"   -o "src/ASF/common/services/usb/class/cdc/device/udi_cdc_desc.o" "../src/ASF/common/services/usb/class/cdc/device/udi_cdc_desc.c" 
C:\Users\bdagenais\Documents\DHP_Kepler\DHP_Kepler-master\Firmware\Debug\Makefile(354,1): error: recipe for target 'src/ASF/common/services/usb/class/cdc/device/udi_cdc_desc.o' failed
		In file included from ../src/asf.h:122:0,
		                 from ../src/CommandResponse/Message/MessageHandler.h:12,
		                 from ../src/config/conf_usb.h:170,
		                 from ../src/ASF/common/services/usb/class/cdc/device/udi_cdc_desc.c:47:
C:\Users\bdagenais\Documents\DHP_Kepler\DHP_Kepler-master\Firmware\src\ASF\common\services\usb\class\cdc\device\udi_cdc.h(582,1): warning: function declaration isn't a prototype [-Wstrict-prototypes]
		 void udi_cdc_flush_rx_buffer();
		 ^~~~
C:\Users\bdagenais\Documents\DHP_Kepler\DHP_Kepler-master\Firmware\src\ASF\common\services\usb\class\cdc\device\udi_cdc.h(583,1): warning: function declaration isn't a prototype [-Wstrict-prototypes]
		 int udi_cdc_get_available_rx_bytes();
		 ^~~
C:\Users\bdagenais\Documents\DHP_Kepler\DHP_Kepler-master\Firmware\src\ASF\common\services\usb\class\cdc\device\udi_cdc.h(584,1): warning: function declaration isn't a prototype [-Wstrict-prototypes]
		 int udi_cdc_get_available_tx_bytes();
		 ^~~
		In file included from ../src/asf.h:132:0,
		                 from ../src/CommandResponse/Message/MessageHandler.h:12,
		                 from ../src/config/conf_usb.h:170,
		                 from ../src/ASF/common/services/usb/class/cdc/device/udi_cdc_desc.c:47:
C:\Users\bdagenais\Documents\DHP_Kepler\DHP_Kepler-master\Firmware\src\KeplerConfiguration.h(14,0): warning: "cpu_ms_2_cy" redefined
		 #define cpu_ms_2_cy(ms, f_cpu) (((uint64_t)(ms) * (f_cpu) / 6 + 999) / 1e3)
		 
		In file included from ../src/ASF/common/services/delay/delay.h:62:0,
		                 from ../src/asf.h:66,
		                 from ../src/CommandResponse/Message/MessageHandler.h:12,
		                 from ../src/config/conf_usb.h:170,
		                 from ../src/ASF/common/services/usb/class/cdc/device/udi_cdc_desc.c:47:
C:\Users\bdagenais\Documents\DHP_Kepler\DHP_Kepler-master\Firmware\src\ASF\common\services\delay\sam\cycle_counter.h(108,0): info: this is the location of the previous definition
		 #  define cpu_ms_2_cy(ms, f_cpu)  \
		 
		In file included from ../src/asf.h:134:0,
		                 from ../src/CommandResponse/Message/MessageHandler.h:12,
		                 from ../src/config/conf_usb.h:170,
		                 from ../src/ASF/common/services/usb/class/cdc/device/udi_cdc_desc.c:47:
C:\Users\bdagenais\Documents\DHP_Kepler\DHP_Kepler-master\Firmware\src\CommandResponse\Message\Messages.h(46,1): warning: "/*" within comment [-Wcomment]
		 /*________________________________|___________________|_________________________________________|___________________________*/
		  
		In file included from ../src/CommandResponse/Message/MessageHandler.h:13:0,
		                 from ../src/config/conf_usb.h:170,
		                 from ../src/ASF/common/services/usb/class/cdc/device/udi_cdc_desc.c:47:
C:\Users\bdagenais\Documents\DHP_Kepler\DHP_Kepler-master\Firmware\src\CommandResponse\Message\Messages.h(46,1): warning: "/*" within comment [-Wcomment]
		 /*________________________________|___________________|_________________________________________|___________________________*/
		  
		In file included from ../src/CommandResponse/Message/MessageHandler.h:22:0,
		                 from ../src/config/conf_usb.h:170,
		                 from ../src/ASF/common/services/usb/class/cdc/device/udi_cdc_desc.c:47:
C:\Users\bdagenais\Documents\DHP_Kepler\DHP_Kepler-master\Firmware\src\ADC\adc.h(23,1): warning: function declaration isn't a prototype [-Wstrict-prototypes]
		 void disable_adc_tc_trigger();
		 ^~~~
		In file included from ../src/Vehicle/CAN/CanFilter.h:13:0,
		                 from ../src/CommandResponse/Message/MessageHandler.h:23,
		                 from ../src/config/conf_usb.h:170,
		                 from ../src/ASF/common/services/usb/class/cdc/device/udi_cdc_desc.c:47:
C:\Users\bdagenais\Documents\DHP_Kepler\DHP_Kepler-master\Firmware\src\Vehicle\CAN\kcan.h(15,25): error: isotp_types.h: No such file or directory
		 #include "isotp_types.h"
		                         ^
		compilation terminated.
		make: *** [src/ASF/common/services/usb/class/cdc/device/udi_cdc_desc.o] Error 1
		Building file: ../src/ASF/sam/drivers/can/can.c
		Invoking: ARM/GNU C Compiler : 6.3.1
		"C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\arm\arm-gnu-toolchain\bin\arm-none-eabi-gcc.exe"  -x c -mthumb -D__SAM4E8C__ -DDEBUG -DBOARD=SAM4E_EK -Dscanf=iscanf -DARM_MATH_CM4=true -Dprintf=iprintf -D__SAM4E16E__ -DUDD_ENABLE  -I"../src/ASF/common/boards" -I"../src/ASF/sam/utils" -I"../src/ASF/sam/utils/header_files" -I"../src/ASF/sam/utils/preprocessor" -I"../src/ASF/thirdparty/CMSIS/Include" -I"../src/ASF/thirdparty/CMSIS/Lib/GCC" -I"../src/ASF/sam/utils/fpu" -I"../src/ASF/common/utils" -I"../src/ASF/sam/utils/cmsis/sam4e/include" -I"../src/ASF/sam/utils/cmsis/sam4e/source/templates" -I"../src/ASF/sam/boards/sam4e_ek" -I"../src/ASF/sam/boards" -I"../src/ASF/common/services/ioport" -I"../src/ASF/common/services/clock" -I"../src/ASF/sam/drivers/pmc" -I"../src" -I"../src/config" -I"../src/ASF/sam/drivers/matrix" -I"../src/ASF/sam/drivers/pio" -I"../src/ASF/common/services/sleepmgr" -I"../src/ASF/common/services/usb" -I"../src/ASF/common/services/usb/class/cdc" -I"../src/ASF/common/services/usb/class/cdc/device" -I"../src/ASF/common/services/usb/udc" -I"../src/ASF/sam/drivers/udp" -I"../src/UI" -I"C:\Users\adeck\Documents\DHP\Firmware\Kepler\KAVI_Firmware_CPP\KeplerFirmware\KeplerFirmware\Debug\src\USB" -I"../src/USB" -I"../src/CommandResponse" -I"../src/CommandResponse/FIFO" -I"../src/CommandResponse/Message" -I"../src/CommandResponse/Error" -I"../src/Vehicle" -I"../src/Vehicle/J1850/VPW" -I"../src/ASF/sam/drivers/tc" -I"../src/ASF/sam/drivers/efc" -I"../src/ASF/sam/services/flash_efc" -I"../src/Security" -I"../src/ASF/sam/drivers/can" -I"../src/RunTimer" -I"../src/ASF/sam/drivers/uart" -I"../src/Console" -I"../../../libs/VehicleCommunicationLib/ISOTP" -I"../src/ASF/sam/drivers/afec" -I"../src/ADC" -I"../src/Filter" -I"../src/Vehicle/CAN" -I"../src/ASF/common/services/delay"  -O0 -fdata-sections -ffunction-sections -mlong-calls -g3 -Wall -mcpu=cortex-m4 -c -pipe -fno-strict-aliasing -Wall -Wstrict-prototypes -Wmissing-prototypes -Werror-implicit-function-declaration -Wpointer-arith -std=gnu99 -ffunction-sections -fdata-sections -Wchar-subscripts -Wcomment -Wformat=2 -Wimplicit-int -Wmain -Wparentheses -Wsequence-point -Wreturn-type -Wswitch -Wtrigraphs -Wunused -Wuninitialized -Wunknown-pragmas -Wfloat-equal -Wundef -Wshadow -Wbad-function-cast -Wwrite-strings -Wsign-compare -Waggregate-return -Wmissing-declarations -Wformat -Wmissing-format-attribute -Wno-deprecated-declarations -Wpacked -Wredundant-decls -Wnested-externs -Wlong-long -Wunreachable-code -Wcast-align --param max-inline-insns-single=500 -mfloat-abi=softfp -mfpu=fpv4-sp-d16 -MD -MP -MF "src/ASF/sam/drivers/can/can.d" -MT"src/ASF/sam/drivers/can/can.d" -MT"src/ASF/sam/drivers/can/can.o"   -o "src/ASF/sam/drivers/can/can.o" "../src/ASF/sam/drivers/can/can.c" 
		Finished building: ../src/ASF/sam/drivers/can/can.c
		Building file: ../src/ASF/sam/drivers/efc/efc.c
		Invoking: ARM/GNU C Compiler : 6.3.1
		"C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\arm\arm-gnu-toolchain\bin\arm-none-eabi-gcc.exe"  -x c -mthumb -D__SAM4E8C__ -DDEBUG -DBOARD=SAM4E_EK -Dscanf=iscanf -DARM_MATH_CM4=true -Dprintf=iprintf -D__SAM4E16E__ -DUDD_ENABLE  -I"../src/ASF/common/boards" -I"../src/ASF/sam/utils" -I"../src/ASF/sam/utils/header_files" -I"../src/ASF/sam/utils/preprocessor" -I"../src/ASF/thirdparty/CMSIS/Include" -I"../src/ASF/thirdparty/CMSIS/Lib/GCC" -I"../src/ASF/sam/utils/fpu" -I"../src/ASF/common/utils" -I"../src/ASF/sam/utils/cmsis/sam4e/include" -I"../src/ASF/sam/utils/cmsis/sam4e/source/templates" -I"../src/ASF/sam/boards/sam4e_ek" -I"../src/ASF/sam/boards" -I"../src/ASF/common/services/ioport" -I"../src/ASF/common/services/clock" -I"../src/ASF/sam/drivers/pmc" -I"../src" -I"../src/config" -I"../src/ASF/sam/drivers/matrix" -I"../src/ASF/sam/drivers/pio" -I"../src/ASF/common/services/sleepmgr" -I"../src/ASF/common/services/usb" -I"../src/ASF/common/services/usb/class/cdc" -I"../src/ASF/common/services/usb/class/cdc/device" -I"../src/ASF/common/services/usb/udc" -I"../src/ASF/sam/drivers/udp" -I"../src/UI" -I"C:\Users\adeck\Documents\DHP\Firmware\Kepler\KAVI_Firmware_CPP\KeplerFirmware\KeplerFirmware\Debug\src\USB" -I"../src/USB" -I"../src/CommandResponse" -I"../src/CommandResponse/FIFO" -I"../src/CommandResponse/Message" -I"../src/CommandResponse/Error" -I"../src/Vehicle" -I"../src/Vehicle/J1850/VPW" -I"../src/ASF/sam/drivers/tc" -I"../src/ASF/sam/drivers/efc" -I"../src/ASF/sam/services/flash_efc" -I"../src/Security" -I"../src/ASF/sam/drivers/can" -I"../src/RunTimer" -I"../src/ASF/sam/drivers/uart" -I"../src/Console" -I"../../../libs/VehicleCommunicationLib/ISOTP" -I"../src/ASF/sam/drivers/afec" -I"../src/ADC" -I"../src/Filter" -I"../src/Vehicle/CAN" -I"../src/ASF/common/services/delay"  -O0 -fdata-sections -ffunction-sections -mlong-calls -g3 -Wall -mcpu=cortex-m4 -c -pipe -fno-strict-aliasing -Wall -Wstrict-prototypes -Wmissing-prototypes -Werror-implicit-function-declaration -Wpointer-arith -std=gnu99 -ffunction-sections -fdata-sections -Wchar-subscripts -Wcomment -Wformat=2 -Wimplicit-int -Wmain -Wparentheses -Wsequence-point -Wreturn-type -Wswitch -Wtrigraphs -Wunused -Wuninitialized -Wunknown-pragmas -Wfloat-equal -Wundef -Wshadow -Wbad-function-cast -Wwrite-strings -Wsign-compare -Waggregate-return -Wmissing-declarations -Wformat -Wmissing-format-attribute -Wno-deprecated-declarations -Wpacked -Wredundant-decls -Wnested-externs -Wlong-long -Wunreachable-code -Wcast-align --param max-inline-insns-single=500 -mfloat-abi=softfp -mfpu=fpv4-sp-d16 -MD -MP -MF "src/ASF/sam/drivers/efc/efc.d" -MT"src/ASF/sam/drivers/efc/efc.d" -MT"src/ASF/sam/drivers/efc/efc.o"   -o "src/ASF/sam/drivers/efc/efc.o" "../src/ASF/sam/drivers/efc/efc.c" 
		Finished building: ../src/ASF/sam/drivers/efc/efc.c
	Done executing task "RunCompilerTask" -- FAILED.
Done building target "CoreBuild" in project "KeplerFirmware.cproj" -- FAILED.
Done building project "KeplerFirmware.cproj" -- FAILED.

Build FAILED.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

**Comment by jeankalud** [comment]
You are missing isotp_types.h

see: https://github.com/openxc/isotp-c

**Comment by beyerch** [comment]
Actually a bunch 'o stuff missing.  Just took a look and found everything.  I will update firmware code in the morning, its been a long day.

Thx!

________________________________

**Comment by beyerch** [comment]
Found issues with uploaded files and will be updating tomorrow AM.

Thanks!

________________________________

**Comment by beyerch** [comment]
Updated, please try again, thanks!
